name = "Tim McCallum"
description = "AgTech & Automation Specialist, Toowoomba QLD, Australia."
keywords = "Toowoomba, Queensland, QLD, Australia, AgTech, Automation"
image = "tpmccallum.jpg" 
theme = "dark"
primary_color = "#1e88e5" 
text_align = "center"
gtag_id = "G-SJPMS5JZ17" 
base_url = "https://tpmccallum.github.io/timothy.mccallum.com.au/" 
[[sections]]
title = "Helping advance Australia's agricultural future through robotics, automation, and intelligent software systems."
description = "Based in Toowoomba, Queensland, I combine over a decade of experience in automotive engineering and advanced software development. I currently support and deploy robotics and autonomous agricultural systems for commercial Australian growers across Queensland and New South Wales."
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections]]
title = "Contact Me"
description = "I am a Renaissance developer with a rare blend of software engineering, agricultural machinery expertise, and real world troubleshooting experience. Based in Toowoomba, QLD, I am a trade qualified automotive engineer with university level software development qualifications and deep experience in Rust, C++, Python, Linux, Unix, and Bash. I deliver practical automation solutions, write software that works in the field, and excel at training, mentoring, and collaborating to achieve measurable outcomes."
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/x/ffffff"
title = "X" 
url = "https://x.com/mistermac2008" 
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram" 
url = "https://www.instagram.com/tpmccallum/" 
[[sections.items]]
icon = "https://cdn.simpleicons.org/github/ffffff"
title = "GitHub"
url = "https://github.com/tpmccallum" # From your original site
[[sections.items]]
icon = "https://cdn.simpleicons.org/medium/ffffff"
title = "Medium"
url = "https://tpmccallum.medium.com/list/publications-d8712a0a9395"
[[sections.items]]
icon = "https://cdn.simpleicons.org/gmail/ffffff"
title = "Email"
url = "mailto:mistermac2008@gmail.com"
[[sections]]
title = "Projects"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Spin: Official Documentation"
description = "Technical Writing Project."
url = "https://github.com/fermyon/developer/graphs/contributors"
[[sections.items]]
title = "SpinKube: Official Documentation"
description = "Technical Writing Project."
url = "https://github.com/spinkube/documentation/graphs/contributors"
[[sections]]
title = "Articles"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Inaugural WebAssembly (Wasm) Summit: Silicon Valley"
description = "Joined industry leaders at a pivotal Google summit in Mountain View to shape WebAssembly’s role in next-gen ecosystems."
url = "https://medium.com/wasm/webassembly-summit-2020-881510ccb0c2"
[[sections.items]]
title = "Running WebAssembly (Wasm) Components From the Command Line"
description = "Learn to build and invoke an exported function from a Rust/Wasm component."
url = "https://bytecodealliance.org/articles/invoking-component-functions-in-wasmtime-cli"
[[sections.items]]
title = "C++ Meets the Open Web"
description = "This article shows you how to write C++ for the Web."
url = "https://medium.com/wasm/c-meets-the-open-web-74fd71e7fc2b"
[[sections.items]]
title = "Wasm-Powered Data Transformation"
description = "Working With Excel And JSON."
url = "https://medium.com/wasm/wasm-powered-data-transformation-working-with-excel-and-json-fb3ccdc952f2"
[[sections.items]]
title = "WebAssembly: Solving Technical Debt"
description = "How WebAssembly Crushes Technical Debt."
url = "https://medium.com/wasm/webassembly-solving-technical-debt-0bb7e390bdcb"
[[sections.items]]
title = "WebAssembly’s Unseen Gap: Why Our Code Might Not Work"
description = "Unpacking the hidden challenges of running Wasm in the wild."
url = "https://medium.com/wasm/webassemblys-unseen-gap-why-our-code-might-not-work-1df65bb1301b"
[[sections.items]]
title = "WASM Component Model: Seamless Compression — C, Rust, and WASM"
description = "Building interoperable Wasm components with C and Rust."
url = "https://medium.com/wasm/wasm-component-model-seamless-compression-c-rust-and-wasm-3b8d52ed8b31"
[[sections.items]]
title = "Leveraging Python Standard Library via WebAssembly"
description = "Explore how Python's extensive libraries, when compiled to WebAssembly, simplify solving complex mathematical problems over the web."
url = "https://www.fermyon.com/blog/leveraging-python-standard-library-via-webassembly"
[[sections.items]]
title = "Persisting Data in WebAssembly Applications Using Redis"
description = "Unleash the power of WebAssembly with Spin 2.0 as we guide you through using Redis for state-of-the-art data persistence in cloud-based applications."
url = "https://www.fermyon.com/blog/persisting_data_in_webassembly_applications_using_redis"
[[sections.items]]
title = "Serverless AI Inferencing Using Python"
description = "Serverless AI Inferencing Using Python: Deploy Python-based serverless AI with Spin effortlessly. Dive into our step-by-step guide to unlock seamless AI inferencing on Fermyon Cloud."
url = "https://www.fermyon.com/blog/serverless-ai-inferencing-using-python"
[[sections.items]]
title = "Can we put the AI in hAIku?"
description = "In a time where Large Language Models (LLMs) are continuing to blossom, do you think that we still hold a discernible edge over Artificial Intelligence (AI) when it comes to writing hauki poetry?"
url = "https://www.fermyon.com/blog/can-we-put-the-ai-in-haiku"
[[sections.items]]
title = "Diving Into Ethereum’s World State"
description = "A deep dive into how Ethereum works."
url = "https://medium.com/cybermiles/diving-into-ethereums-world-state-c893102030ed"
[[sections.items]]
title = "Mastering Ethereum (GitHub Contribution)"
description = "Contributed to Andreas M. Antonopoulos and Gavin Wood’s open-source book."
url = "https://github.com/ethereumbook/ethereumbook"
[[sections]]
title = "Scholarly Works That Reference My Articles"
description = "My articles have been cited in top-tier Journals (such as Springer, Sage, IEEE) by scholars from across the globe including regions such as Germany, China, Switzerland and U.S.A."
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
title = "Fuzzm: Finding Memory Bugs through Binary-Only Instrumentation and Fuzzing of WebAssembly"
description = "Publisher: arXiv.org (Cornell University)."
url = "https://arxiv.org/abs/2110.15433"
[[sections.items]]
title = "An Ethereum bill of lading under the UNCITRAL MLETR"
description = "Publisher: Sage Journals."
url = "https://journals.sagepub.com/doi/abs/10.1177/1023263X20904316"
[[sections.items]]
title = "Using Ethereum blockchain to store and query pharmacogenomics data via smart contracts"
description = "Publisher: BMC Medical Genomics (Springer Nature)."
url = "https://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-020-00732-x"
[[sections.items]]
title = "Ethereum Analytics"
description = "Publisher: ETH Zürich (Switzerland)."
url = "https://ethz.ch/content/dam/ethz/special-interest/mtec/chair-of-entrepreneurial-risks-dam/documents/dissertation/master%20thesis/Master_thesis-Athina_Voulgari.pdf"
[[sections.items]]
title = "Blockchain Technology in the Oil and Gas Industry: A Review of Applications, Opportunities, Challenges, and Risks"
description = "Publisher: IEEE Xplore."
url = "https://ieeexplore.ieee.org/abstract/document/8675726"
[[sections.items]]
title = "Everything Old is New Again: Binary Security of WebAssembly"
description = "Publisher: The Advanced Computing System Association (USE-NIX) – 29th Security Symposium."
url = "https://www.usenix.org/conference/usenixsecurity20/presentation/lehmann"
[[sections.items]]
title = "Symbolic Execution of Wasm Bytecode for Cross-Platform Smart Contract Vulnerability Detection"
description = "Publisher: arXiv.org (Cornell University)."
url = "https://arxiv.org/abs/2007.15510"
[[sections.items]]
title = "Blockchain als verteilte Netzwerktechnologie"
description = "Publisher: Springer Link."
url = "https://link.springer.com/chapter/10.1007/978-3-658-29822-7_2"
[[sections.items]]
title = "Einer Blockchain-basierten IoT-Infrastruktur mit Ethereum und Swarm"
description = "Publisher: HAW Hamburg."
url = "https://reposit.haw-hamburg.de/bitstream/20.500.12738/9127/1/BA_Artur_Iablokov.pdf"
[[sections]]
title = "Awards"
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
title = "AMP Tomorrow Maker"
description = "2015 AMP Tomorrow Maker award recipient."
url = "https://www.amp.com.au/ampfoundation"
[[sections.items]]
title = "EOS Global Hackathon: Most Valuable Mentor"
description = "Most Valuable Mentor award recipient at the 2018 EOS Global Hackathon event in Sydney, Australia."
url = "https://x.com/EOSIO/status/1026027344668942336"
